package org.apache.airavata.datacat.worker.parsers.chem.gaussian.old;
/* The following code was generated by JFlex 1.3.5 on 11/14/02 9:15 AM */

import java_cup.runtime.Symbol;
import org.apache.airavata.datacat.worker.parsers.chem.gaussian.DefaultGaussianParser;

import java.io.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 11/14/02 9:15 AM from the specification file
 * <tt>file:/home/dodi/new_qcrjm/gaussian/method.flex</tt>
 */
public class MethodLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int IGNOREALL = 2;
  final public static int ITER1 = 2;
  final public static int YYINITIAL = 0;
  final public static int ITER = 1;

  /**
   * Translates characters to character classes
   */
  final private static char [] yycmap = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,
     0,  7,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,
     0, 20, 10,  9, 21, 19,  0,  6,  0, 22,  0,  0,  0, 24, 15, 23,
    18, 12, 13, 11, 16, 14,  0,  0,  0, 17, 25,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,
     4,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /**
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = {
        0,    26,    52,    78,   104,   130,   156,   182,   208,   234,
      260,    78,    78,   286,   312,   338,    78,   364,   390,   416,
      442,   468,   494,    78,   520,   546,   572,   598,   624,   650,
      676,   702,   728,   754,   780,   806,   832,   858,   884,   910,
      936,   962,   988,  1014,  1040,  1066,  1092,  1118,  1144,  1170,
     1196,    78,  1222,  1248,  1274,  1300,  1326,    78,    78,  1352,
     1378,  1404,  1430,  1456,  1482,    78
  };

  /**
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 =
    "\2\4\1\5\32\4\1\6\2\4\1\7\2\4\1\10"+
    "\3\4\1\11\46\4\34\0\1\12\33\0\1\13\34\0"+
    "\1\14\1\15\33\0\1\16\35\0\1\17\15\0\1\20"+
    "\34\0\1\21\37\0\1\22\35\0\1\23\14\0\1\24"+
    "\31\0\1\25\47\0\1\26\13\0\1\27\43\0\1\30"+
    "\36\0\1\31\12\0\1\32\51\0\1\33\11\0\1\34"+
    "\30\0\1\35\32\0\1\36\35\0\1\37\14\0\1\40"+
    "\3\0\1\41\4\0\1\42\44\0\1\43\33\0\1\44"+
    "\34\0\1\45\11\0\1\46\53\0\1\47\30\0\1\50"+
    "\26\0\1\51\13\0\1\52\54\0\1\53\21\0\1\54"+
    "\42\0\1\55\5\0\1\56\55\0\1\57\11\0\1\60"+
    "\53\0\1\61\3\0\1\62\52\0\1\63\27\0\1\64"+
    "\36\0\1\65\5\0\1\66\46\0\1\67\43\0\1\70"+
    "\2\0\1\71\47\0\1\72\34\0\1\73\10\0\1\74"+
    "\31\0\1\75\31\0\1\76\31\0\1\77\31\0\1\100"+
    "\31\0\1\101\31\0\1\102\27\0";

  /**
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  0,  9,  1,  1,  1,  1,  1,  0,  0,  9,  9,  0,  0,  0,
     9,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     0,  0,  0,  9,  0,  0,  0,  0,  0,  9,  9,  0,  0,  0,  0,  0,
     0,  9
  };

  /** the input device */
  private Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the
   * matched text
   */
  private int yycolumn;

  /**
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
  public static boolean DEBUG = false;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public MethodLexer(Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public MethodLexer(InputStream in) {
    this(new InputStreamReader(in));
  }

  /**
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[1508];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /**
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead,
                       yy_buffer, 0,
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead,
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream
   */
  final public void yyreset(Reader reader) throws IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos =
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state;
            yy_markedPos_l = yy_currentPos_l;
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 11:
          {
   if (DEBUG) System.out.println("MethodFlex: Found G1");
   if (DEBUG) System.out.println(yytext());
 try{
     //PrintStream temp = new PrintStream(new FileOutputStream(Settings.defaultDirStr +
    PrintStream temp = new PrintStream(new FileOutputStream(System.getProperty("java.io.tmpdir")
            + File.separator + DefaultGaussianParser.randomNum +"runtype1"));
     temp.print(yytext());
     if (DEBUG) System.out.println(yytext());}
   catch (IOException ie){ System.out.println("Error in Gaussian Lexer");}
     yybegin(IGNOREALL);
     return new Symbol(MethodSym.RUNTYP);
     }
        case 67: break;
        case 12:
          {
   if (DEBUG) System.out.println("MethodFlex: Found G2");
   if (DEBUG) System.out.println(yytext());
 try{
     //PrintStream temp = new PrintStream(new FileOutputStream(Settings.defaultDirStr +
     PrintStream temp = new PrintStream(new FileOutputStream( System.getProperty("java.io.tmpdir")
             + File.separator + DefaultGaussianParser.randomNum +"runtype1"));
     temp.print(yytext());
     if (DEBUG) System.out.println(yytext());}
   catch (IOException ie){ System.out.println("Error in Gaussian Lexer");}
     yybegin(IGNOREALL);
     return new Symbol(MethodSym.RUNTYP);
     }
        case 68: break;
        case 16:
          {
  if  (DEBUG) System.out.println("MethodFlex: Found opt ");
   if (DEBUG) System.out.println(yytext());
 try{
     //PrintStream temp = new PrintStream(new FileOutputStream(Settings.defaultDirStr +
    PrintStream temp = new PrintStream(new FileOutputStream(System.getProperty("java.io.tmpdir")
            + File.separator + DefaultGaussianParser.randomNum +"runtype1"));
     temp.print(yytext());
     if (DEBUG) System.out.println(yytext());}
   catch (IOException ie){ System.out.println("Error in Gaussian Lexer");}

     yybegin(IGNOREALL);
     return new Symbol(MethodSym.RUNTYP);
     }
        case 69: break;
        case 23:
          {
   if (DEBUG) System.out.println("MethodFlex: Found CBS-Q");
   if (DEBUG) System.out.println(yytext());
 try{
     //PrintStream temp = new PrintStream(new FileOutputStream(Settings.defaultDirStr +
	 PrintStream temp = new PrintStream(new FileOutputStream(System.getProperty("java.io.tmpdir")
             + File.separator + DefaultGaussianParser.randomNum +"runtype1"));
     temp.print(yytext());
     if (DEBUG) System.out.println(yytext());}
   catch (IOException ie){ System.out.println("Error in Gaussian Lexer");}
     yybegin(IGNOREALL);
     return new Symbol(MethodSym.RUNTYP);
     }
        case 70: break;
        case 51:
          {
   if (DEBUG) System.out.println("MethodFlex: RUNTYP=ENERGY");
   if (DEBUG) System.out.println(yytext());
 try{
     //PrintStream temp = new PrintStream(new FileOutputStream(Settings.defaultDirStr +
	 PrintStream temp = new PrintStream(new FileOutputStream(System.getProperty("java.io.tmpdir")
             + File.separator + DefaultGaussianParser.randomNum +"runtype1"));
     temp.print("energy");
     if (DEBUG) System.out.println(yytext());}
   catch (IOException ie){ System.out.println("Error in Gaussian Lexer");}
     yybegin(IGNOREALL);
     return new Symbol(MethodSym.RUNTYP);
     }
        case 71: break;
        case 58:
          {
   if (DEBUG) System.out.println("MethodFlex: RUNTYP=ENERGY");
   if (DEBUG) System.out.println(yytext());
 try{
     //PrintStream temp = new PrintStream(new FileOutputStream(Settings.defaultDirStr +
     PrintStream temp = new PrintStream(new FileOutputStream(System.getProperty("java.io.tmpdir")
             + File.separator + DefaultGaussianParser.randomNum +"runtype1"));
     temp.print("optimize");
     if (DEBUG) System.out.println(yytext());}
   catch (IOException ie){ System.out.println("Error in Gaussian Lexer");}
     yybegin(IGNOREALL);
     return new Symbol(MethodSym.RUNTYP);
     }
        case 72: break;
        case 65:
          {
    if (DEBUG) System.out.println("MethodFlex: Found Gaussian 98");
           yybegin(ITER);
	   return new Symbol(MethodSym.FOUNDITER);
   }
        case 73: break;
        case 3:
        case 4:
        case 5:
        case 6:
        case 7:
        case 8:
          {  }
        case 74: break;
        case 57:
          {
   if (DEBUG) System.out.println("MethodFlex: RUNTYP=GRADIENT");
   if (DEBUG) System.out.println(yytext());
 try{
     //PrintStream temp = new PrintStream(new FileOutputStream(Settings.defaultDirStr +
    PrintStream temp = new PrintStream(new FileOutputStream(System.getProperty("java.io.tmpdir")
            + File.separator + DefaultGaussianParser.randomNum +"runtype1"));
     temp.print("gradient");
     if (DEBUG) System.out.println(yytext());}
   catch (IOException ie){ System.out.println("Error in Gaussian Lexer");}
     yybegin(IGNOREALL);
     return new Symbol(MethodSym.RUNTYP);
 }
        case 75: break;
        default:
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new java_cup.runtime.Symbol(MethodSym.EOF); }
          }
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   * <a href="http://meissner.v0.net/msd.htm">meissner.v0.net/msd.htm</a>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] class_fields = MethodSym.class.getFields();
      for (int i = 0; i < class_fields.length; i++) {
        if (class_fields[i].getInt(null) == token) {
          return class_fields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   * <a href="http://meissner.v0.net/msd.htm">meissner.v0.net/msd.htm</a>
   */
  public java_cup.runtime.Symbol debug_next_token() throws IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, i.e. it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java MethodLexer <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        MethodLexer scanner = null;
        try {
          scanner = new MethodLexer( new FileReader(argv[i]) );
          while ( !scanner.yy_atEOF ) scanner.next_token();
        }
        catch (FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
