package org.apache.airavata.datacat.worker.parsers.chem.gaussian;
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Thu Feb 09 15:19:43 CST 2006
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class GOPTSym {
  /* terminals */
  public static final int MGRAD = 10;
  public static final int RmsGrad = 7;
  public static final int Energ = 5;
  public static final int MaxGrad = 6;
  public static final int ENERGY = 9;
  public static final int EOF = 0;
  public static final int ITERATION = 8;
  public static final int NSearch = 4;
  public static final int RGRAD = 11;
  public static final int error = 1;
  public static final int SCFDONE = 3;
  public static final int FOUNDITER = 2;
}

