
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Oct 03 11:18:10 CDT 2006
//----------------------------------------------------

package org.apache.airavata.datacat.worker.parsers.chem.gaussian;

/** CUP generated class containing symbol constants. */
public class WavefunctionSym {
  /* terminals */
  public static final int RUNTYP = 4;
  public static final int SCFDONE = 3;
  public static final int error = 1;
  public static final int FOUNDITER = 2;
  public static final int RUNTYP1 = 5;
  public static final int EOF = 0;
}

